apiVersion: v1
kind: Service
metadata:
  name: ctf-service
spec:
  selector:
    app: ctf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  clusterIP: 10.0.171.239
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
