apiVersion: v1
kind: Service
metadata:
  name: witcherportal-service
spec:
  selector:
    app: witcherportal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  clusterIP: 10.0.171.240
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.128
